version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: kandahar_postgres
    restart: always
    environment:
      POSTGRES_USER: kandahar_user
      POSTGRES_PASSWORD: kandahar_password
      POSTGRES_DB: kandahar_electronics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
